---
author: "Marcelino Guerra"
date: "2020-11-22T09:10:11-03:00"
description: ""
draft: true
tags: []
title: Quem manda na política cearense?
---

As eleições municipais! Nada melhor do que elas para mostrar como as legendas são apenas instrumentos de poder a serviço dos políticos. O bizarro apoio do Partido dos Trabalhadores (PT) ao Partido do Movimento Democrático Brasileiro (PMDB) em 648 alianças municipais é sintomático; em Aiuaba, interior do Ceará, PMDB e PT se juntaram a Democratas (DEM), Partido da Social Democracia Brasileira (PSDB), Partido da República (PR), Partido Progressista (PP) e Partido Comunista do Brasil (PC do B) para, de fato, formar a coligação “por uma Aiuaba de todos”.

Mesmo para quem mora em Fortaleza, não é exatamente trivial perceber que Heitor Férrer e Roberto Cláudio trocaram de legenda. Nas eleições de 2012, para a prefeitura, Heitor Férrer - 3º lugar naquele primeiro turno - era do Partido Democrático Trabalhista (PDT), e, atualmente, está no Partido Socialista Brasileiro (PSB). Já Roberto Cláudio fez o caminho inverso: se elegeu prefeito pelo PSB e agora está no PDT, não antes de "marcar um dez" no Partido Republicano da Ordem Social (PROS).

Aproveitando o ano eleitoral e levando em conta esse frequente troca-troca de partidos, refazemos o mapa político do Ceará.
